INSERT INTO joblist (id,correlation_id,"name",created_at,created_by,modified_at,modified_by,status,"source",destination,"type",sub_type,"action",action_details,progress,history,extra_data,priority,"rank")
select substring(replace(to_char(clock_timestamp(),'yyyymmddhh24missus') || (to_char(random()*1e9,'000000000')),' ',''),1,27),
concat('Correlation Id - ', md5(RANDOM()::TEXT)),
concat('Job - ', md5(RANDOM()::TEXT)),
NOW() - (random() * (interval '90 days')),
concat('Creator - ', md5(RANDOM()::TEXT)),
NOW() - (random() * (interval '90 days')),
concat('Modifier - ', md5(RANDOM()::TEXT)),
(array['created', 'queued', 'running', 'paused', 'finished', 'failed'])[floor(random() * 6 + 1)],
concat('Source - ', md5(RANDOM()::TEXT)),
concat('Destination - ', md5(RANDOM()::TEXT)),
(array['encoding', 'proxy', 'techqc', 'streaming'])[floor(random() * 4 + 1)],
concat('SubType - ', md5(RANDOM()::TEXT)),
concat('Action - ', md5(RANDOM()::TEXT)),
concat('Action Details - ', md5(RANDOM()::TEXT)),
floor(random() * 101)::int,
concat('History - ', md5(RANDOM()::TEXT), md5(RANDOM()::TEXT), md5(RANDOM()::TEXT), md5(RANDOM()::TEXT)),
concat('Extra Data - ', md5(RANDOM()::TEXT), md5(RANDOM()::TEXT), md5(RANDOM()::TEXT), md5(RANDOM()::TEXT)),
(array[10, 20, 30, 40, 50])[floor(random() * 5+1)]::int,
floor(random() * 1501)::int
end from pg_catalog.generate_series(1,100);
